services:
  - type: web
    name: park-ranger-tools
    env: python
    plan: free
    buildCommand: ""
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
    startCommand: PYTHONPATH="$PYTHONPATH:/opt/render/project/src" python frontend/app.py --host 0.0.0.0 --port $PORT
    autoDeploy: true
